# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required
warnings_are_errors: false


script:
  - docker build -t gpurcore/gpurcublas .

  

  