# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: ruby
dist: trusty
sudo: required
warnings_are_errors: false


before_install:
  - docker build -t gpurcore/gpurcublas .

  

  