// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cublasGemm
void cublasGemm(SEXP A, SEXP B, SEXP C, std::string type, const int type_flag);
RcppExport SEXP _gpuRcublas_cublasGemm(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP typeSEXP, SEXP type_flagSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    Rcpp::traits::input_parameter< SEXP >::type C(CSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const int >::type type_flag(type_flagSEXP);
    cublasGemm(A, B, C, type, type_flag);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gpuRcublas_cublasGemm", (DL_FUNC) &_gpuRcublas_cublasGemm, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpuRcublas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
